(()=>{'use strict';
const $=s=>document.querySelector(s), audio=$('#globalAudio'); if(!audio)return;
const storeKey='frankEnglishLearningV3';
const state=Object.assign({seconds:0,plays:{},mastered:{},starred:{},offsets:{},lastArticle:1,streakDays:{},dictationScores:[]},JSON.parse(localStorage.getItem(storeKey)||'{}'));
const save=()=>localStorage.setItem(storeKey,JSON.stringify(state));
let currentId=0,timing=null,lastTick=0,shadow=false,pauseTimer=null;
const panel=document.createElement('aside');panel.className='learning-panel';panel.innerHTML=`<div class="ls-head"><h3>英语学习中心</h3><button class="ls-close">✕</button></div><div class="ls-grid"><div class="ls-card"><b id="lsMinutes">0</b><span>累计分钟</span></div><div class="ls-card"><b id="lsArticles">0</b><span>已学文章</span></div><div class="ls-card"><b id="lsStars">0</b><span>重点词</span></div></div><div class="ls-progress"><i id="lsProgressBar"></i></div><div class="ls-section"><h4>同步校准</h4><div class="ls-row"><button id="offMinus">−0.1秒</button><span class="ls-offset" id="offsetLabel">0.0秒</span><button id="offPlus">+0.1秒</button><button id="offReset">重置</button></div><small>高亮太快就加，高亮太慢就减；每篇单独保存。</small></div><div class="ls-section"><h4>精听模式</h4><div class="ls-row"><button id="shadowBtn">跟读暂停：关</button><button id="dictationBtn">当前句听写</button><button id="markSentence">收藏当前词</button></div></div><div class="ls-section"><h4>我的重点词</h4><div class="ls-word-list" id="starList"></div></div><div class="ls-section"><div class="ls-row"><button id="exportData">导出学习数据</button><button id="resetData">清空数据</button></div></div>`;document.body.append(panel);
const fab=document.createElement('button');fab.className='learning-fab';fab.textContent='📊 学习中心';document.body.append(fab);
const toast=document.createElement('div');toast.className='ls-toast';document.body.append(toast);
const dialog=document.createElement('div');dialog.className='ls-dictation';dialog.innerHTML=`<div class="ls-dialog"><h3>当前句听写</h3><p>先听一句，再输入你听到的英文。</p><textarea id="dictInput" placeholder="Type what you heard..."></textarea><div class="ls-row"><button id="dictReplay">重播本句</button><button id="dictCheck">检查</button><button id="dictClose">关闭</button></div><div class="ls-result" id="dictResult" hidden></div></div>`;document.body.append(dialog);
const say=t=>{toast.textContent=t;toast.classList.add('show');setTimeout(()=>toast.classList.remove('show'),1600)};
function today(){return new Date().toISOString().slice(0,10)}
function updateStats(){state.streakDays[today()]=true;$('#lsMinutes').textContent=Math.floor(state.seconds/60);$('#lsArticles').textContent=Object.keys(state.plays).length;$('#lsStars').textContent=Object.keys(state.starred).length;$('#lsProgressBar').style.width=`${Math.min(100,Object.keys(state.mastered).length/40*100)}%`;renderStars();save()}
function idFromSrc(){const m=decodeURIComponent(audio.currentSrc||audio.src).match(/(\d{2})\.mp3/i);return m?Number(m[1]):0}
function offset(){return Number(state.offsets[currentId]||0)}
function updateOffset(){currentId=idFromSrc()||currentId;$('#offsetLabel').textContent=`${offset().toFixed(1)}秒`}
function currentToken(){const words=[...document.querySelectorAll('#a'+currentId+' .sync-word')];return words.find(w=>w.classList.contains('sync-active'))||null}
function sentenceRange(){const active=currentToken();if(!active)return null;const para=active.closest('.para.en');return {text:para.innerText.trim(),para}}
function renderStars(){const box=$('#starList');box.innerHTML='';Object.entries(state.starred).slice(-60).reverse().forEach(([key,v])=>{const b=document.createElement('button');b.className='ls-chip';b.textContent=v.word;b.title=`第${v.article}篇`;b.onclick=()=>{document.getElementById('a'+v.article)?.scrollIntoView({behavior:'smooth'});};box.append(b)});if(!box.children.length)box.textContent='点击正文中的高亮词，再点“收藏当前词”。'}
function applyOffsetPatch(){if(window.__lsOffsetPatched)return;window.__lsOffsetPatched=true;const desc=Object.getOwnPropertyDescriptor(HTMLMediaElement.prototype,'currentTime');if(!desc)return; /* player reads native time; visual correction is applied by shifting timing data after fetch below */}
const nativeFetch=window.fetch.bind(window);window.fetch=async function(input,init){const res=await nativeFetch(input,init);if(typeof input==='string'&&/timing\/\d{2}\.json/.test(input)){const data=await res.clone().json();const id=Number((input.match(/(\d{2})\.json/)||[])[1]);const off=Number(state.offsets[id]||0);if(off){data.tokens?.forEach(t=>{t.start+=off;t.end+=off});if(data.sentences)data.sentences.forEach(s=>{s.start+=off;s.end+=off});}return new Response(JSON.stringify(data),{status:res.status,statusText:res.statusText,headers:res.headers});}return res};
fab.onclick=()=>{panel.classList.toggle('open');updateStats();updateOffset()};$('.ls-close').onclick=()=>panel.classList.remove('open');
$('#offMinus').onclick=()=>{currentId=idFromSrc()||currentId;if(!currentId)return say('请先播放一篇文章');state.offsets[currentId]=Math.round((offset()-.1)*10)/10;save();updateOffset();say('已保存，重新点本篇播放后生效')};
$('#offPlus').onclick=()=>{currentId=idFromSrc()||currentId;if(!currentId)return say('请先播放一篇文章');state.offsets[currentId]=Math.round((offset()+.1)*10)/10;save();updateOffset();say('已保存，重新点本篇播放后生效')};
$('#offReset').onclick=()=>{delete state.offsets[currentId];save();updateOffset();say('本篇偏移已重置')};
$('#shadowBtn').onclick=e=>{shadow=!shadow;e.target.classList.toggle('on',shadow);e.target.textContent=`跟读暂停：${shadow?'开':'关'}`};
$('#markSentence').onclick=()=>{const w=currentToken();if(!w)return say('请先播放到一个单词');const key=currentId+':'+w.textContent.toLowerCase();state.starred[key]={word:w.textContent,article:currentId,at:audio.currentTime};w.classList.add('ls-starred');save();updateStats();say('已收藏 '+w.textContent)};
$('#dictationBtn').onclick=()=>{if(!sentenceRange())return say('请先播放到一句话');audio.pause();$('#dictInput').value='';$('#dictResult').hidden=true;dialog.classList.add('open')};$('#dictClose').onclick=()=>dialog.classList.remove('open');$('#dictReplay').onclick=()=>{audio.currentTime=Math.max(0,audio.currentTime-5);audio.play()};
$('#dictCheck').onclick=()=>{const target=(sentenceRange()?.text||'').toLowerCase().match(/[a-z']+/g)||[];const given=$('#dictInput').value.toLowerCase().match(/[a-z']+/g)||[];const set=new Set(target);const correct=given.filter(x=>set.has(x)).length;const score=Math.round(correct/Math.max(1,target.length)*100);state.dictationScores.push({article:currentId,score,date:Date.now()});save();$('#dictResult').hidden=false;$('#dictResult').textContent=`得分：${score}\n\n原句：${sentenceRange()?.text||''}`;updateStats()};
$('#exportData').onclick=()=>{const blob=new Blob([JSON.stringify(state,null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='english-learning-data.json';a.click();URL.revokeObjectURL(a.href)};
$('#resetData').onclick=()=>{if(confirm('确定清空本机学习记录吗？')){localStorage.removeItem(storeKey);location.reload()}};
audio.addEventListener('loadedmetadata',()=>{currentId=idFromSrc();state.lastArticle=currentId;state.plays[currentId]=(state.plays[currentId]||0)+1;lastTick=audio.currentTime;updateStats();updateOffset()});
audio.addEventListener('timeupdate',()=>{if(!audio.paused){const now=audio.currentTime,delta=now-lastTick;if(delta>0&&delta<2)state.seconds+=delta;lastTick=now;if(Math.floor(state.seconds)%10===0)save()}currentId=idFromSrc()||currentId});audio.addEventListener('seeked',()=>lastTick=audio.currentTime);
let lastPara=null;new MutationObserver(()=>{const w=currentToken();if(w){document.querySelectorAll('.sync-word.ls-current-sentence').forEach(x=>x.classList.remove('ls-current-sentence'));const p=w.closest('.para.en');if(p!==lastPara){lastPara=p;if(shadow&&pauseTimer){clearTimeout(pauseTimer)}if(shadow&&p){pauseTimer=setTimeout(()=>{if(!audio.paused){audio.pause();say('跟读暂停：读完后按空格继续')}},Math.max(1200,(p.innerText.split(/\s+/).length*.32)*1000))}}Object.values(state.starred).forEach(v=>{if(v.article===currentId)[...document.querySelectorAll('#a'+currentId+' .sync-word')].filter(x=>x.textContent.toLowerCase()===v.word.toLowerCase()).forEach(x=>x.classList.add('ls-starred'))})}}, {subtree:true,attributes:true,attributeFilter:['class']}).observe(document.body,{subtree:true,attributes:true,attributeFilter:['class']});
applyOffsetPatch();updateStats();
})();
